export enum ActionTypes {
    SET_TOKEN = 'SET_TOKEN',
    REMOVE_TOKEN = 'REMOVE_TOKEN',
    SET_USERINFO = "SET_USERINFO",
    REMOVE_USERINFO = 'REMOVE_USERINFO',
    SET_REMEMBER = "SET_REMEMBER"
}